

+incdir+$(CURRENT_PATH)/../RTL
+incdir+$(CURRENT_PATH)/../SIM

$(CURRENT_PATH)/../RTL/radix2.v
$(CURRENT_PATH)/../RTL/ROM_2.v
$(CURRENT_PATH)/../RTL/ROM_4.v
$(CURRENT_PATH)/../RTL/ROM_8.v
$(CURRENT_PATH)/../RTL/ROM_16.v
$(CURRENT_PATH)/../RTL/shift_1.v
$(CURRENT_PATH)/../RTL/shift_2.v
$(CURRENT_PATH)/../RTL/shift_4.v
$(CURRENT_PATH)/../RTL/shift_8.v
$(CURRENT_PATH)/../RTL/shift_16.v
$(CURRENT_PATH)/../RTL/FFT.v

$(CURRENT_PATH)/../SIM/FFT_tb.v